name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    # otata has exclusive paths depending on the OS:
    #
    # macOS has launchd and keychain
    # Linux has the systemd user manager
    strategy:
      matrix:
        include:
          - os: macos-latest
            other: linux
          - os: ubuntu-latest
            other: darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - run: test -z "$(gofmt -l .)"
      - run: go vet ./...
      - run: GOOS=${{ matrix.other }} go vet ./...
      - run: go test ./...
